window-width = 1200
window-height = 800

[fonts]
size = 18

[fonts.regular]
family = "Hack"
weight = 600

[fonts.bold]
family = "Hack"
weight = 800

[fonts.italic]
family = "Hack"
weight = 600
style = "italic"

[fonts.bild-italic]
family = "Hack"
weight = 800
style = "italic"

[navigation]
mode = "NativeTab"
macos-hide-window-buttons = false

### config.toml ends here
